### ISSUE TITLE
Define runtime test data model

### ISSUE THREAD

**Issue by alexandrasp** [kernelci/kernelci-api#204]
Currently, we are not storing any information about the tests, just if they pass or fail. It is essential to save detailed information to create proper reports and track regressions, especially in cases where tests are falling.

Similarly to kernel builds (https://github.com/kernelci/kernelci-pipeline/issues/277), we need to define the data model(s) for storing test results.

- [ ] Common data model for any type of test defined and implemented
       For example: log fragment, platform information...
- [ ] Tested locally with `kver` and `kunit`
- [ ] Tested on staging with `kunit` and `baseline-x86` in LAVA

**Comment by gctucker** [comment]
@mgalka Can you comment on how this fits within the development roadmap for the API / Pipeline?
