### ISSUE TITLE
Redis deployment

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#259]
The API relies on a Redis instance, mostly as a low-level Pub/Sub engine.  The default setup is to run it in a local container with `docker-compose`, for similar reason than MongoDB (#258) it's worth considering how to run this in the Cloud.  One option could be to create a Redis resource in Azure via the marketplace.  Another option is to run it in a container like the main API service, since Redis shouldn't need too much work to maintain (no persistent storage, low compute requirements).

This is closely related to evaluating deployment options for the main API service and pipeline services as per #18.

- [x] Redis resource created in Azure
- [ ] Tested with local API instance connected to the Azure Redis
      _Note: This may be skipped if we can just test it with the API service running in the same cluster to avoid opening a port etc._
- [ ] Tested with Kubernetes deployment of the API service also running in Azure
- [ ] Redis run as container in Kubernetes deployment and tested with API also in Kubernetes
- [ ] Summary and conclusion about which option seems to be the most appropriate

**Comment by gctucker** [comment]
One issue is that the Redis Server resource in the MS Azure marketplace is not currently covered by our sponsorship:
![azure-redis-vm-costs-001](https://github.com/kernelci/kernelci-api/assets/3894008/728b89d0-9f34-46ba-9588-b713900f9a1c)

So the next step is to discuss how to get this covered, either by Microsoft or by the LF project budget.

**Comment by gctucker** [comment]
Taking a look at the "Redis with Ubuntu 19.04 Free by Cognosys" option also.

**Comment by gctucker** [comment]
The Cognosys option didn't seem to convincing, also it's a VM.  Looking into deploying this in Kubernetes instead now with the "Bitnami package for Redis" from the Azure marketplace.  This shouldn't incur any costs not covered by the sponsorship.

**Comment by gctucker** [comment]
Documentation: https://docs.bitnami.com/azure/infrastructure/redis/

**Comment by gctucker** [comment]
Deployment created successfully via the Azure portal:
```
kernelci@00d6c35c126d:~$ kubectl get pods
NAME                              READY   STATUS    RESTARTS   AGE
kciapistaging1-redis-master-0     1/1     Running   0          2m29s
kciapistaging1-redis-replicas-0   1/1     Running   0          73s
kciapistaging1-redis-replicas-1   1/1     Running   0          101s
kciapistaging1-redis-replicas-2   1/1     Running   0          2m31s
kernelci@00d6c35c126d:~$ kubectl logs kciapistaging1-redis-master-0
1:C 20 Jun 2023 08:29:42.247 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 20 Jun 2023 08:29:42.247 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just std
1:C 20 Jun 2023 08:29:42.247 # Configuration loaded
1:M 20 Jun 2023 08:29:42.248 * monotonic clock: POSIX clock_gettime
1:M 20 Jun 2023 08:29:42.248 * Running mode=standalone, port=6379.
1:M 20 Jun 2023 08:29:42.248 # Server initialized
1:M 20 Jun 2023 08:29:42.249 * Reading RDB base file on AOF loading...
1:M 20 Jun 2023 08:29:42.249 * Loading RDB produced by version 7.0.11
1:M 20 Jun 2023 08:29:42.249 * RDB age 455 seconds
1:M 20 Jun 2023 08:29:42.249 * RDB memory usage when created 0.82 Mb
1:M 20 Jun 2023 08:29:42.249 * RDB is base AOF
1:M 20 Jun 2023 08:29:42.249 * Done loading RDB, keys loaded: 0, keys expired: 0.
1:M 20 Jun 2023 08:29:42.249 * DB loaded from base file appendonly.aof.1.base.rdb: 0.000 seconds
1:M 20 Jun 2023 08:29:42.249 * DB loaded from append only file: 0.000 seconds
1:M 20 Jun 2023 08:29:42.249 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
1:M 20 Jun 2023 08:29:42.249 * Ready to accept connections
```

**Comment by gctucker** [comment]
To add web application routing from the outside to the Redis instance (ingress) in Azure, first steps:
```
$ az extension add --name aks-preview
The installed extension 'aks-preview' is in preview.
$ az aks enable-addons --addons web_application_routing --resource-group=kernelci-api-staging --name=kciapistaging1-redis-master
```
Documentation: https://learn.microsoft.com/en-us/azure/aks/web-app-routing?tabs=without-osm

Then the next steps seem to be to create a DNS zone as it doesn't seem possible to route directly from the public IP address without a hostname.  I'll take a look at that next.

**Comment by gctucker** [comment]
Ah also I just checked it was possible to open a local connection to the Redis service from within the main container:
```
$ kubectl exec -it kciapistaging1-redis-master-0 -- redis-cli 
127.0.0.1:6379> 
```

**Comment by gctucker** [comment]
It looks like there isn't a huge advantage of using this approach compared to just running our own container in a k8s deployment.  So I think we'll resolve this issue and stick to plain k8s deployment instead.

**Comment by gctucker** [comment]
Closing as the current consensus is to run Redis as part of the k8s deployment of services as per #269
