### ISSUE TITLE
Early Access checklist

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#296]
We would like to host an instance of the new API to provide early access to a number of public users.  This would be half-way between the staging instance we currently have and a definitive production instance.  It should be online and available at any time, with just some updates when required.  So the uptime and stability should be much better than the staging instance, but we don't need to guarantee the quality of service or plan carefully each update like for a real production deployment.

The data associated with this instance may not be transferred into the definitive production instance, but it should be persistent as much as possible.

Here's a checklist of things that need to be done before we can start the early access scheme:
- [x] MongoDB deployment (Atlas)
  - [x] Atlas free instance created
  - [x] Tested with API service
- [x] Storage
  - [x] Azure storage account created
  - [x] Azure storage supported by KernelCI
  - [x] Tested with staging API instance
- [x] API services
  - [x] Kubernetes deployment tested locally with MiniKube
  - [x] Kubernetes development cluster set up in Azure
  - [x] Deployed in Azure
- [x] Pipeline services
  - [x] Kubernetes deployment tested locally with MiniKube
  - [x] Deployed in Azure
- [x] User accounts
  - [x] Models and entry points updated to create user accounts
  - [x] Support for user groups created (with `admin` group as special case)
  - [x] Users can update their own password
- [x] Node ownership
  - [x] Owner and group added to Node model
  - [x] Rules implemented to allow only owner or group members to update a Node document
- [x] Documentation
  - [x] Getting Started page updated
  - [x] Documentation section about user accounts added / updated
  - [x] Early Access (beta testing) page added
  - [x] Timeline for transition to new API documented
  - [x] Legacy system marked as deprecated
- [x] Add an email field to user profile
- [x] Email test reports

**Comment by gctucker** [comment]
The Early Access phase started on the planned day for the milestone (4th Sept).
